"hamster_plasma_membrane_geneLevel"
"hamster_plasma_membrane_protLevel"

"hamster_surface_and_plasma_membrane_geneLevel"
"hamster_surface_and_plasma_membrane_protLevel"

"hamster_surface_geneLevel"
"hamster_surface_protLevel"


"monkey_plasma_membrane_geneLevel"
"monkey_plasma_membrane_protLevel"

"monkey_surface_and_plasma_membrane_geneLevel"
"monkey_surface_and_plasma_membrane_protLevel"

"monkey_surface_geneLevel"
"monkey_surface_protLevel"


"human_plasma_membrane_geneLevel"
"human_plasma_membrane_protLevel"

"human_surface_and_plasma_membrane_geneLevel"
"human_surface_and_plasma_membrane_protLevel"

"human_surface_geneLevel"
"human_surface_protLevel"

"human_CRISPR_geneLevel"
"human_CRISPR_protLevel"